#!/bin/bash

USER=$(whoami)
HOME=/home/$USER
DOTFILES=/$HOME/.dotfiles

printf "Running install scripts"

sudo $DOTFILES/zsh/install
sudo $DOTFILES/vim/install
sudo $DOTFILES/tmux/install


printf "Creating symlinks"

rm $HOME/.zshrc && ln -s $DOTFILES/zsh/.zshrc $HOME
rm $HOME/.vimrc && ln -s $DOTFILES/vim/.vimrc $HOME
rm $HOME/.tmux.conf && ln -s $DOTFILES/tmux/.tmux.conf $HOME

