set -g default-shell /bin/zsh
set -g repeat-time 1000
set -g focus-events on

set -as terminal-features ",xterm-kitty:sync" # tmux does not auto-detect kitty's Sync

# options
set -g detach-on-destroy off
set -g set-titles on
set -g mouse on
set -g set-clipboard on # send copies to the system clipboard via OSC 52
set -g status off
# set -g status-right ""
set -g history-limit 10000
set -sg escape-time 0 # No delay for escape key press

setw -g mode-keys vi # vi mode to copy text
setw -g monitor-activity on
setw -g xterm-keys on # allow ctrl + arrow keys

# required for image.nvim
set -gq allow-passthrough on # allow ctrl + b to pass through to the terminal
set -g visual-activity off # disable visual bell

# keybiddings
set -g prefix C-a
unbind C-b
bind C-a send-prefix # changes ctrl + b to ctrl + a

# splits
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# join panes
bind j join-pane

# resize panes
bind-key -r C-h resize-pane -L 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-k resize-pane -U 5
bind-key -r C-l resize-pane -R 5

# layouts
bind-key H select-layout main-horizontal
bind-key V select-layout main-vertical
bind-key T select-layout tiled

# vim like text copy
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# adds an alias to reload tmux file
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Setup plugins
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'christoomey/vim-tmux-navigator' # allows seamless navigation between vim and tmux 
set -g @vim_navigator_prefix_mapping_clear_screen ''
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tpm'

# Catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux
run ~/.tmux/plugins/tpm/tpm

